version: '3.1'

services:

  jenkins:
    image: dagman62/jenkins:2.122
    container_name: jenkins
    environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

